[package]
name = "red-blox/vault"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
	"default.project.json",
	"lib",
	"lib/**",
	"LICENSE",
	"wally.toml",
	"README.md",
]

[dependencies]
Future = "red-blox/future@1.0.0"
Signal = "red-blox/signal@1.0.0"
